name: Python CI

on: [push] # This workflow will run when code is pushed to the repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2 # This step checks out your code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x # You can specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Install any required Python packages

    - name: Run tests
      run: |
        python hello.py # Replace with your Python script
